### ISSUE TITLE
sprinkles() missing 1 required positional argument: 'img'

### ISSUE THREAD

**Issue by linminhtoo** [jcgrundy/sprinkles#1]
Hello,

Thanks for your effort in making this! However, I was trying to add this transformation into my fast.ai model and encountered the above error. It seems sprinkles() strictly needs an image argument, unlike the other xtra_tfms in the fast.ai library. Is there any way to overcome this? 
 
![image](https://user-images.githubusercontent.com/25001874/85791306-30b4f680-b764-11ea-8644-ad48666e1d40.png)

**Comment by jcgrundy** [comment]
Hi linminhtoo,

At the moment the function does not work in the transformations pipe. I made this before using the fast.ai library so was calling the function on my datasets once rather than iteratively from a generator. But thank you for reminding me about this I will take a look over the next week and see if I can get this working.

**Comment by jcgrundy** [comment]
Hello again,

I have just pushed an update which includes a `xtra_tfms()` compatible function. I have tested it on my end but not extensively so there may be some issues I am not yet aware of. Secondly it seems quite slow at the moment when sprinkles are being added in each batch. I first wanted to get it working but will look to try and optimise it next if I can.

**Comment by linminhtoo** [comment]
Hi jcgrundy, thank you so much for taking your precious time to add this! I really really appreciate it :) Alright, please let me know if you manage to optimise it :) Wish I could help with the coding, but I am only a beginner still trying to fumble around things :/

**Comment by jcgrundy** [comment]
No problem at all, it had been on my list of things 'to get to' for a very long time as well. I'm sure you will get there quicker than you think with the coding!
